USE kitchenmanager_db;
ALTER TABLE orders DROP CONSTRAINT CK__orders__status__4D94879B;
ALTER TABLE orders ADD CONSTRAINT CK_orders_status CHECK (status IN ('NEW', 'ACCEPTED', 'COOKING', 'READY', 'COMPLETED', 'CONFIRMED', 'DELIVERING', 'DELIVERED', 'CANCELLED'));